### ISSUE TITLE
Use of process in index.js

### ISSUE THREAD

**Issue by diestrin** [reactjs/redux#1404]
Not exactly an issue of redux, but [this line of code](https://github.com/reactjs/redux/blob/master/src/index.js#L15) is the one to blame to not be able to use this library with NativeScript

Since redux and angular2 are making its way, and in the other hand angular2 and nativescript are in the same path, I started writing my first nativescript application using angular2 and redux, but sadly, index.js makes a call to process.env, which doesn't exist in nativescript.

Not sure if the nativescript guys can make something to fix this (like including this and some other variables in the js engine) or if you guys can make some kind of validation (like `'process' in global` or something), because for now, the entire library wont work in nativescript just for that small check at the beginning.

Feel free to close this issue if you don't see the point on changing your code to support this lib. For other users interested in using this, what I did was (typescript):
```
declare type Process = any;
declare var process: Process;
process = {env: {}};
```
This will make it work.

**Comment by gaearon** [comment]
The CommonJS build (which is what you seem to be using) uses Node idioms. I think this is expected. It uses `module.exports` too which doesn’t exist in the browser.

Since your bundler of choice is able to handle `module.exports`, it should also be able to “envify” the code. Like the error message says just below, you can use [loose-envify](https://github.com/zertosh/loose-envify) with Browserify, or `DefinePlugin` with Webpack.

If your bundler of choice supports CommonJS but *not* envification, I think it is worth filing an issue with your bundler of choice. In the meantime you can use the workaround you suggested above.

Finally, note that you absolutely don’t *have to* use the CommonJS build. You can find already envified UMD builds at `redux/dist/redux.js` (development) and `redux/dist/redux.min.js` (production). Since they are already envified, they don’t include references to the `process` object.

**Comment by VeRsu5** [comment]
Can I know in which file should I add this 3 lines so as to get redux working with nativescript? Thank You 👍
