### ISSUE TITLE
redux load local storage at first

### ISSUE THREAD

**Issue by aaeronn** [reactjs/redux#1421]
I have a react app like where I have `App.js` which includes my `Headers` and `Footers` ..

In there I am storing my `state` to local storage.. After storing I can retrieve it .. 

But I am having problem on loading it .. In my browser when I do `localstorage['key']` it gives me the data but I am unable to load after browser refresh.. 

Where should I load it first ? 

I have `Root.js` :

    `class Root extends Component {
      render() {
        const { store } = this.props
        return (
          <Provider store={store}>
              <ReduxRouter />
          </Provider>
        )
      }
    }
    
    Root.propTypes = {
      store: PropTypes.object.isRequired
    }
    
    export default Root`

and `index.js` at outer level :

    `const store = configureStore()
    
    
    render(
    
      	<Root store={store} />,
      document.getElementById('root')
    )`

Where should I load my `localStorage` ?

Need help . I need to know what is called first in react so that I can make a call to load `localStorage` there .. If it is not bad idea

**Comment by joncys** [comment]
Do you follow the pattern of allowing initial state to be set in the `configureStore` method?

If so, you could just pass it inside the method call as in `const store = configureStore(localStorage.getItem('key');`.

`index.js` is being loaded first in your example and it bootstraps the whole app by rendering out the `Root` component contained within `Root.js`.

**Comment by gaearon** [comment]
Hi, thanks for posting.

This is an issue tracker for Redux. Please ask usage questions on a dedicated Q&A site like StackOverflow. If we answer your question here, it will get lost (because GitHub search is not very well designed), and somebody is going to ask it again and again. On the other hand, on StackOverflow, you will get an answer that will serve as the definitive answers for everybody else in the future.

Feel free to post a link to your StackOverflow question, and I’ll do my best to reply.
