### ISSUE TITLE
[Question] Is This an Anti-Pattern?

### ISSUE THREAD

**Issue by hnordt** [reactjs/redux#1497]
I have a promise middleware that handle promises, this middleware dispatches a new action with the same type but with a different payload on success/failure.

I want to know if it's a anti-pattern or is not recommended:

```js
export function saveState() {
  return (dispatch, getState) => {
    return dispatch({
      type: SAVE_STATE,
      payload: localforage.setItem('state', getState())
    })
  }
}
```

For this use case, dispatching an action without an action creator is ok?

**Comment by gaearon** [comment]
Dispatching an action without an action creator is always OK. Action creators are just a popular way of organizing the code. If you don’t like them or feel they are not needed in a particular case, don’t use them. It is completely up to you.

**Comment by hnordt** [comment]
Thank you @gaearon !

**Comment by tracker1** [comment]
While not an anti-pattern, I tend to do the following...  All action types are defined in a constants module, this way I'm less inclined to mis-type in the action creator, or reducer side... I also use [redux-actions](https://www.npmjs.com/package/redux-actions) to create simple action creators, this way I always `dispatch(actionName(args))` even when using `redux-thunk`, which I use with `async` actions (via babel).

I also break my code up into `./feature/feature-name/subfeature-name...` in that I have base `reducers.js` that then references each feature's reducers... from there, each feature has it's own constants, these I prefix...   

```
// feature/foo/constants.js
const DO_SOMETHING = 'FOO_DO_SOMETHING';
```

So that my action types won't conflict between features...  each feature may also have an `api.js` module, so that the action creators' logic is separated from any calls into foreign data/systems.

It does take a little discipline to do this, but in the end, adding features is a manner of mostly repeating these patterns...  components/pages/controls are under their respective feature, and I also have some common bits under `feature/shared/*`
