### ISSUE TITLE
Documentation: es6 Map and Set in the state are not documented

### ISSUE THREAD

**Issue by andruhon** [reactjs/redux#1499]
I did not find in the documentation how one should or should not use things like es6 Map and Set with Redux.

It seems like a new map should be created every time when we 'modify' it in the reducer, but I'm not sure that it is correct.

**Comment by gaearon** [comment]
I don’t think it’s a good idea to use them in Redux because they are optimized for mutability. If you want to have something efficient with similar semantics, consider using Immutable.js.

**Comment by andruhon** [comment]
Can this be mentioned somewhere in the docs, that it is not a good idea?

**Comment by mohammedabualsoud** [comment]
Yes, I'm not able to use ES6 map it seems it just deal with Objects, and array only.

**Comment by markerikson** [comment]
You _can_ use Maps and Sets as state values, but it's not recommended due to serializability concerns.  In addition, the built-in `combineReducers` utility expects to work with plain JS objects, so if you use a Map as part of your state tree, you would need to use other reducer handling instead of `combineReducers`.

**Comment by adrienjt** [comment]
FYI, I have implemented generic map and set reducers using plain JS objects in [redux-data-structures](https://redux-data-structures.js.org/):
https://github.com/adrienjt/redux-data-structures/blob/master/src/reducers/map.js
https://github.com/adrienjt/redux-data-structures/blob/master/src/reducers/set.js

**Comment by ChuckJonas** [comment]
@adrienjt can you add a usage example gist for the map type above?

**Comment by ChuckJonas** [comment]
Not sure if this is what @markerikson means by "serializability concerns", but for example if you try to do things like export/import your entire state with json, any maps in your reducer state will not properly be initialized.  The basic issue is outlined here: http://2ality.com/2015/08/es6-map-json.html

**Comment by spedy** [comment]
@markerikson Maps are to "heavy" for me. Too much code needed to handle uniquenes and as you said serializability concerns... I am reflecting on the idea of using Sets to help maintain my states. In this example https://redux.js.org/usage/structuring-reducers/normalizing-state-shape `allIds` for example would be a Set.
```

**Comment by markerikson** [comment]
@spedy Actually, Redux Toolkit's `createEntityAdapter` maintains that "IDs list" as an array, _and_ already does all the work of updating it for you :)  Use that:

https://redux.js.org/tutorials/essentials/part-6-performance-normalization#managing-normalized-state-with-createentityadapter

**Comment by karmaniverous** [comment]
> I don’t think it’s a good idea to use them in Redux because they are optimized for mutability. If you want to have something efficient with similar semantics, consider using Immutable.js.

[`serify-deserify`](https://www.npmjs.com/package/@karmaniverous/serify-deserify) reversibly transforms unserializable values into serializable ones, and back. It natively supports `BigInt`, `Date`, `Map`, and `Set`, and you can easily add support for custom types.

The package includes a Redux middleware that applies the `serify` transformation on the way into the store. Wrap retrieval functions in the `deserify` function in order to transform the results to the appropriate type.

Full disclosure: I am the package creator!
