### ISSUE TITLE
Module not found importing from 'redux/store' and 'redux/modules/auth'

### ISSUE THREAD

**Issue by ThatsNinja** [reactjs/redux#1512]
I've got an app using redux and webpack. Webpack's dev server works fine with the below:
```
import { isLoaded as isAuthLoaded, load as loadAuth } from 'redux/modules/auth';
```
... and...
```
import store from 'redux/store';
```

However, when I do the webpack production build, the build flails while importing, returning:
```
Module not found: Error: Cannot resolve module <module>
```
... for both of the above.

Apologies if it's determined that this is more properly a webpack question, but I'm fairly bewildered here. What, please, would be the best way to import these modules consistently?

**Comment by mbensch** [comment]
That's because they are not part of the `redux` package. You are probably tinkering around with https://github.com/erikras/react-redux-universal-hot-example. You should ask your question there. 

The way you're importing is fine in general but you should be importing them from the local path. (Assuming your file is in the same root as the `redux/modules` folder)

```
import { isLoaded as isAuthLoaded, load as loadAuth } from './redux/modules/auth';
```

Your import fails because it tries to locate the modules in the `redux` package.

**Comment by gaearon** [comment]
Yup! We don’t have this stuff in Redux.

**Comment by sompylasar** [comment]
@ThatsNinja it is probably caused by the `NODE_PATH` environment variable not set properly.
https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders

**Comment by sompylasar** [comment]
In https://github.com/erikras/react-redux-universal-hot-example the `NODE_PATH` variable is set by the `better-npm-run` configured in `package.json`: https://github.com/erikras/react-redux-universal-hot-example/blob/master/package.json#L80

**Comment by ThatsNinja** [comment]
@mbensch Nailed it. It would seem that the webpack build is a bit more pessimistic in terms of loading things from the relative filesystem. The fact that I was building with a dependency named `redux`, and had things to import from a relative path down `./redux` was breaking the build.

Pre-pending the `./` on the import path fixed in webpack build, and webpack-dev-server is happy as well.

**Comment by sompylasar** [comment]
@ThatsNinja there was no `./` for a reason -- when you'll have components that are nested deeper, and you'll need to reference something from a top level, a relative path would be inconvenient to write and unmaintainable to refactor; so, you'd better figure out why `redux/modules/...` does not work with webpack as expected.

**Comment by mbensch** [comment]
@sompylasar Generally I agree. The problem is that the local folder is called redux and he also has the redux package installed. I don't use Webpack so I don't know if it's smart enough to resolve that without running into a naming conflict (i.e. look in `./node_modules` first and if it's not found look in the configured `resolve.modulesDirectories`). @ThatsNinja Maybe a better way than relative paths: After skimming through Webpack's docs the first thing I'd try is creating a local `lib` folder in your project root and passing that to Webpack's `resolve.modulesDirectories` option.

**Comment by sompylasar** [comment]
@mbensch I use the same (or similar) boilerplate with `redux` directory, and it works perfectly with both webpack and node resolving properly.

**Comment by mbensch** [comment]
@sompylasar Then I assume Webpack is smart enough to figure that out. But if you look at the Webpack configure that's shipped with the boilerplate you'll see that they list the 'src' directory before the 'node_modules' directory so I assume it takes precedent when Webpack tries to resolve the path.

**Comment by sompylasar** [comment]
@mbensch yes, that should be what makes it work.
