### ISSUE TITLE
Have you ever thought about investing the reducer logic

### ISSUE THREAD

**Issue by benzen** [reactjs/redux#1517]
This is more an open question than an issue.

Currently reducers are organised by sub-parts of the state, or at least it's the default way.
And each reducer recieve actions.

So we've got something like this
````js
//here state is a subpart of the whole state
const counterReducer = (state, action) => {
  switch(action.type) {
    case: 'inc': return state+1;
    case 'dec': return state-1;
   default: return state
  }
}
const reducer = combineReducers({
  counter: counterReducer
});

dispatch({type: 'inc'});
````

What if we make this the other way arround, and at the creation of the main reduced, we make create a map of action type to reducer ?

We will got something like this:

```js
//here the state is the whole state
const incReducer = (state, actionParams...) => {
  return Object.assign(state, {counter: state.counter+1})
};

const reducer = combineReducer({
  'inc': incReducer
});

dispatch('inc', actionParams...)
```

It seams to me that this model is simpler, but i could be wrong, and there is probably a reason not to go this way. I hope someone will see this reason and will help me to see the light.

**Comment by gaearon** [comment]
The point of decoupling reducers from actions is that many reducers can handle the same action independently in different ways. What you’re suggesting would make changes to the reducer logic harder because any time you want to handle some new action, you have to wire up the relevant reducers all over again.

I will close but please feel free to continue the discussion and offer specific examples (such as a rewrite of our example projects with this technique) if you consider this way of doing things to be beneficial.
