### ISSUE TITLE
connect() blocks GSAP animation

### ISSUE THREAD

**Issue by talexand** [reactjs/redux#1520]
We've got a project going that wraps routed view components in ReactTransitionGroups for animation purposes, but when adding `connect()` to them, the animation doesn't run--in fact, ComponentWillAppear and other lifecycle methods from TransitionGroup don't fire. Happens with both decorator and composition calls on a class.

Some relevant snippets:

### route

```js
import ReactTransitionGroup from 'react-addons-transition-group';
import { Router, browserHistory } from 'react-router';

const transitionWrap = (component, myKey) =>
        () => (
          <ReactTransitionGroup>
           { React.createElement(component, { key: myKey }) }
          </ReactTransitionGroup>
        );

const routeConfig = [
  {
    path: '/', component: AppContainer,
    childRoutes: [
      { path: '/somepage', component: transitionWrap(SomePage, browserHistory.createKey()) }
    ]
  }
];
```

### component

```js
import ReactDOM from 'react-dom';
import React from 'react';
import { connect } from 'react-redux';
import 'gsap';

class SomePage extends React.Component {
  componentWillAppear() {
      this.component = ReactDOM.findDOMNode(this);
      this.component.style.opacity = 0;

      const tl = new TimelineMax();
      tl.to(this.component, 1, { opacity: 1 }, 'opacityUp');
      tl.from(this.component, 1, { 'margin-top': '300px' }, 'opacityUp-=.5');
    }

    render() {
      return (
        <p>I should animate up, but I will not if connected.</p>
      );
    }
}

export default connect()(SomePage);
```

Our workaround is to abstract the content of a view component into smaller connected components, which is good practice, but we wanted to make sure the issue is documented.

### environment

- Redux ^3.0.4
- React: ^0.14.7
- react-addons-transition-group: ^0.14.3
- react-redux: ^4.0.0
- GSAP: ^1.18.0

**Comment by gaearon** [comment]
Please see https://github.com/reactjs/react-redux/issues/303. The issue occurs because ReactTransitionGroup API predates higher order components and wasn’t really thought out with them in mind. Putting special “pseudo lifecycle hooks” on the component does not work here because the group sees the *wrapped* component generated by `connect()` rather than the one you wrote. I don’t think we can offer any nice solution without running into tens of different corner cases where such solution would not work so I’m inclined not to try at all. Your best bet would then be either to wrap connect()ed components into regular components where you can declare those hooks, monkeypatch the class returned from `connect()` to have them on the prototype, or just stop using ReactTransitionGroup and start using something like react-motion instead. React is also going to introduce an Animated API for the web so that may help too.

**Comment by talexand** [comment]
Thanks for the info. Sorry for the dupe, an issue search for "animation" didn't turn up #303.

**Comment by gaearon** [comment]
Yeah, no problem. Definitely not an obvious one but hopefully will become less relevant as better alternatives to `ReactTransitionGroup` come up. Thanks for a detailed writeup and environment information.
