### ISSUE TITLE
Is testing a reducer using the store an antipattern?

### ISSUE THREAD

**Issue by thomastuts** [reactjs/redux#1530]
Is it considered an antipattern to test reducers using the full store instead of just the reducer itself? One of my actions is async using redux-thunk and most of my testing logic (a card game) is based on cards being played or not (this logic is handled in that thunk action) and the store's state.

If I test just the reducer instead of the entire store, the redux-thunk middleware doesn't work since I'm testing just the reducer. I don't feel like mocking out my entire store for testing purposes is going to be productive though, since I already have a fully functioning store (the real one) I can use instead.

More concretely: I would run my tests using `store.dispatch(someActionCreator(someVariable))` and then assert on `store.getState()` instead of testing just the reducer (e.g. `reducer(state, someActionCreator(someVariable))` and assert on the state result that is returned from that reducer).

It kind of feels okay to do this since all of the logic is contained in the reducer which the store exposes. I was just wondering if testing your reducers like this is a big no-no.

**Comment by borisyankov** [comment]
It is not an anti-pattern. But it is more of an integration test than a unit-test.
You will find integration tests can fail for many reasons, because they depend on a lot of interconnected code.
Mocking the store is likely worth it.

**Comment by jwbay** [comment]
It sounds like you just want to test your thunks? Testing thunk actions in isolation is usually pretty straightforward. You can pretend to be redux-thunk in a test by just calling the action.

```js
const dispatchSpy = createSpy() //from sinon, jasmine, whatever
myThunkAction(someVariable)(dispatchSpy, someState)
```

You can then assert that dispatch was called with your expected actions given some state.

**Comment by gaearon** [comment]
There are no big no-nos; it is your code and you decide how to work with it. In general I would test action creators separately from reducers because they answer different questions. Even is you use Redux Thunk you can still test the reducer directly using the actual final actions it emits. And you can test the thunk action creator separately as well— either [like this](https://github.com/reactjs/redux/issues/1530#issuecomment-198591080) or with something like [redux-mock-store](https://github.com/arnaudbenard/redux-mock-store). But of course you can also test everything together too, as noted correctly in https://github.com/reactjs/redux/issues/1530#issuecomment-198286324.
