### ISSUE TITLE
Remove lodash dependency

### ISSUE THREAD

**Issue by caseyhoward** [reactjs/redux#1544]
It looks like the only thing needed from lodash is isPlainObject. Would it be possible to create a dependency on lodash.isplainobject instead (https://www.npmjs.com/package/lodash.isplainobject)? The examples use other things in lodash, so those could either be brought in separately or all of lodash can be a devDependency.

**Comment by jdalton** [comment]
The `lodash` and `lodash-es` deps are used by the `redux` package to allow others to bundle it with a reduced footprint. Lodash is likely already in your npm cache so not a burden.

**Comment by adamdonahue** [comment]
The examples use `merge`, `union`, and `zip`, as well.

**Comment by gaearon** [comment]
Lodash is technically a dependency because we require a module from it in the CommonJS build. It doesn’t negatively affect the result app build size in any sensible way because we only require that particular module from it. I have no reasons to believe that removing Lodash dependency has any benefits for us, and it certainly has downsides (such as having to support that module ourselves and keep a copy of it in React Redux which also happens to use it).

I am closing because I don’t see a rationale for *why* this change would be for the better. That said please feel free to explain in this issue, and if there are reasonable concerns that I missed, we can reopen. Thanks!

**Comment by caseyhoward** [comment]
@adamdonahue It can still be a dev dependency

@jdalton @gaearon Thanks for the feedback. I'm using jspm to build my project. I need it the final output to be as small as possible. Since redux is such a small library, I ended up just copying it directly into my project and making some modifications and removing a couple features I didn't need, so I don't really care about getting lodash removed anymore. All I know is that when I compile with the real redux, I end up with a file 10kb larger than when I use the version of redux I created in my project. BTW, redux and lodash are awesome projects. Thanks.

**Comment by gaearon** [comment]
>All I know is that when I compile with the real redux, I end up with a file 10kb larger (both minified) than when I use the version of redux I created in my project.

This looks like an issue with jspm rather than Redux. Maybe worth filing a bug there.
