### ISSUE TITLE
Created a boilerplate app, what's the best place to put it into?

### ISSUE THREAD

**Issue by paulmillr** [reactjs/redux#1550]
So we've created [the app boilerplate](https://github.com/brunch/with-redux). Starting a new app is as simple as that: `brunch new dir -s redux && cd dir && brunch watch --server`. Much simpler than webpack. The app would also receive hot reload just in a bit.

I think this is useful for beginners. What is the best place to add the info?

**Comment by Aweary** [comment]
If approved it would go in [docs/introduction/Ecosystem.md](https://github.com/reactjs/redux/blob/master/docs/introduction/Ecosystem.md). You can always make a PR if you think it would be beneficial to the community.

**Comment by gaearon** [comment]
We’ve shied away from adding boilerplates to Ecosystem because of the monstrosities those usually are.

This one looks pretty simple but if we merge this, we’ll also need to be on the lookout for similar Browserify, Webpack, and Rollup examples so that it doesn’t appear we are promoting Brunch specifically.

I’d say for now it’s best to submit a PR to https://github.com/xgrommx/awesome-redux and https://github.com/markerikson/react-redux-links. If you’d like to compile an up-to-date list of simple boilerplates for different bundlers, then I think we can add them all together to Ecosystem page.

Cheers!
