### ISSUE TITLE
Update React component by dispatching action from non-react component

### ISSUE THREAD

**Issue by rasmuswoelk** [reactjs/redux#1585]
Hi

I'm trying to update the cart-button on a project when the user adds an item to the cart.

I have build parts of the site in React.js - like the cart, the cart button etc. I'm dispatching an action that is supposed to update the card quantity from a non-react component like this:

    import { dispatch } from 'redux';
    import { updateCart } from '../../actions/cart_actions';
    import configureStore from '../../store/configureStore'
    var store = configureStore();

and then..
    
    store.dispatch(updateCart(response));

The action **is dispatched** and **the state is updated**. The cart-button component is connected via. react-redux connect() function. But somehow it isn't updating the component with the new quantity.

When I dispatch an action from within my cart React component it works fine.

I might be missing something obvious. Any suggestions?

**Comment by markerikson** [comment]
If your component isn't updating, it's almost always because your reducer is mutating your state directly instead of returning a copy.  The Redux FAQ page has some more info on that: http://redux.js.org/docs/FAQ.html#react-not-rerendering .

Also, this question is probably better suited for Stack Overflow.  You might want to post it over there.

**Comment by rasmuswoelk** [comment]
@markerikson I will take a look at it. Thanks!

And you are probably right :+1:

**Comment by rasmuswoelk** [comment]
http://stackoverflow.com/questions/36457424/update-react-component-by-dispatching-action-from-non-react-component
