### ISSUE TITLE
Reducer middleware to detect unhandled actions

### ISSUE THREAD

**Issue by bruth** [reactjs/redux#1662]
I wrote this [small function](https://gist.github.com/bruth/5cf17d36dd4f1c3bcf0e4c40f5f844e6) this weekend that wraps the root reducer and compares the state before and after an action is handled. If the state has not changed, then the action is considered "unhandled". This has helped quite a bit when debugging why some actions were not having any impact on application state.

I have two questions:
- Is there anything that already exists that solves this problem? Could the check be more robust?
- If not, is there is any interest in this being available on NPM? If so, is there a recommended package.json for developer tools?

**Comment by markerikson** [comment]
https://github.com/socialtables/redux-unhandled-action looks like it does pretty much the same thing.  (This is part of why I have my [Redux addons catalog](https://github.com/markerikson/redux-ecosystem-links) - I was able to check the [dev tools page](https://github.com/markerikson/redux-ecosystem-links/blob/master/devtools.md) to see if I'd added something like that already.)

Also, given that the reducer _should_ be returning new object references for immutably updated state, a reference equality check _should_ be sufficient rather than a deep equals, and a lot cheaper too.

**Comment by bruth** [comment]
Brilliant, thanks for the information!
