### ISSUE TITLE
Production version

### ISSUE THREAD

**Issue by buzinas** [reactjs/redux#1677]
Looking at Redux, I can see that there are lots of expections handling, such as:

```javascript
if (!isPlainObject(action)) {
  throw new Error(
    'Actions must be plain objects. ' +
    'Use custom middleware for async actions.'
  )
}
```

I know that the minified version is already tiny enough (~2kb after gzip), but I think that most of those errors are for development use, and shouldn't exist in a production/minified version.

In React, if we set our `NODE_ENV` to `'production'`, they remove lots of those exceptions handling, and this decreases the code size considerably.

Wouldn't be good to do the same in Redux?

**Comment by Aweary** [comment]
Redux is already pretty small, and I think most of these errors are essential. If the invariants they check are violated redux will likely throw a more cryptic error somewhere else in the code path.

**Comment by buzinas** [comment]
@Aweary But those errors should **never** happen in production, right?

Most of them are `TypeError`, and if you use TypeScript, for example, you catch them before runtime. If you don't, you'll obviously catch that during development, and only if you're making an *enormous* mistake, there'll be an error like this in production.

Although it's pretty small (as I already said), it can be even smaller - **much** smaller, in fact, probably ~60% smaller, or something like that.

**Comment by Aweary** [comment]
I'd assume they never *should* happen, and a typing system should prevent >95% of situations where it might, but I'd be interested in hearing what @gaearon or @timdorr think about it. There's been [some community support](https://github.com/facebook/react/issues/2686) for better production error handling in React, though redux is much simpler so I'd assume most people won't have a problem with this.

**Comment by timdorr** [comment]
React and Angular have production error messages for much the same reason: Your application code isn't statically analyzable (at least not in JavaScript), so you're always going to have some error that slips through the test suite. It happens. 

Rather than producing unhelpful errors like the classic "Cannot read property 'x' of undefined", having some way to point to the source of the issue is going to be drastically more helpful to deciphering what's going on. 

They may seem wasteful, but so is something like Rollbar or another error tracker, since it doesn't do anything if your code works perfectly. But for the same reasons you add tools like that, you need some amount of error handling for when things go wrong. And the closer to the error point that you can get, the better.

**Comment by buzinas** [comment]
OK, thanks!
