### ISSUE TITLE
Logic within render for the container in redux-async example

### ISSUE THREAD

**Issue by vamsiampolu** [reactjs/redux#1724]
I notice that the render method in the async example has a lot of complex logic, I split the logic out into multiple smaller components within the render method. Is this an anti-pattern?

The code is in the gist [here](https://gist.github.com/vamsiampolu/14594f5782c818cc39e08d1f7ab6a427.js)

**Comment by gaearon** [comment]
Defining them *inside* `render()` is definitely an anti-pattern. React will not be able to diff those effectively because they have a new `type` on every render.

However, defining them *outside* `render()` is great and is better than fat `render()` methods. The examples in Redux repo are far from perfect examples of React best practices, and there is much to improve there.
