### ISSUE TITLE
Redux store.getState is not immutable

### ISSUE THREAD

**Issue by partyhardy** [reactjs/redux#1739]
I love redux and was a little surprised to see that getState or accessing any part of the state doesn't return a copy of the state. Is there a reason not to return Object.assign({}, "store.state")?

**Comment by smashercosmo** [comment]
@partyhardy I think, that the main reason is performance. Copy object every time you want to get your state is obviously not a very good practice. And even if you copy it, it won't be deeply immutable. And deep copying is even less performant. So, if you're worrying about suddenly mutating your state, just deep freeze it in dev mode or use libraries like immutable.js or seamless-immutable, that will throw an error on attempt to mutate state.

**Comment by gaearon** [comment]
@smashercosmo is correct. `Object.assign()` is shallow so it only copies one level deep. Copying deeper comes with a big perf penalty and disables any optimizations that we can get from comparing the references to check if something changed. We also don’t want to use something like `deep-freeze` by default because it also has performance penalties and impacts correctness (we can’t just enable it in DEV and disable in PROD because the behavior would be different).

**Comment by markerikson** [comment]
There's also some dev tools that will warn you if you're mutating.  See the [DevTools#Linting](https://github.com/markerikson/redux-ecosystem-links/blob/master/devtools.md#linting) section of my Redux addons catalog.
