### ISSUE TITLE
Dispatching Store Events From Services With Ducks Redux Approach

### ISSUE THREAD

**Issue by RajnishDashora** [reactjs/redux#1821]
We are using the Ducks Redux approach in our codebase and would like to know your opinion about a certain situation. From our API service, we get a response (common for calls), that we need to update the store with. 

The question is, since the API service is not really a React Component, is it okay to import the store in the service file and then dispatch an update from there? Or, would you suggest an alternate approach?

**Comment by sompylasar** [comment]
Redux does not depend on React, and it's totally okay to dispatch actions from anywhere except the reducers.

As an example, a set of actions can be dispatched during the server-side rendering to initialize the store.

**Comment by markerikson** [comment]
This is a usage question, and as such should be asked on Stack Overflow rather than the issues list.

Per the FAQ, the general advice is to avoid directly referencing the store, and rely on basic dependency injection wherever possible.  This is usually done via middleware.  See http://redux.js.org/docs/FAQ.html#store-setup-multiple-stores .
