### ISSUE TITLE
Double checking

### ISSUE THREAD

**Issue by babakness** [reactjs/redux#1884]
Hey guys, I just want to double check something. I've seen code where the action creator does something like this in tutorials

```
actionCreate(){
  dispatch(...)
  restAPICall()
}
```

This seems incorrect. That it should be more like

```
actionCreate(){
  dispatch()
}

restAPIReducer(){
  ...
  restAPICall().then( ... => {
   dispatch(success())
  }).catch( ... => {
  dispatch(fail())
 })
}
```

Thanks

**Comment by gaearon** [comment]
Could you please use StackOverflow for usage questions? We use issue tracker for bug reports.

As for your question, no, the original code is probably using Redux Thunk. Since reducers can't do anything asynchronous, I'm not sure how your second code snippet could work. Please consult `async` example in this repo and corresponding docs on the website for more information.

**Comment by babakness** [comment]
Ok. I noticed other entries marked as discussion.

Imagine setting a router path in an action (for a browser) then dispatching. The route change should happen in response to a state change; the action creator shouldn't change route then merely record state by dispatching it. 

I suppose that Thunk can work in the case of async data loading to save time but it isn't really clean conceptually.

**Comment by gaearon** [comment]
>The route change should happen in response to a state change; the action creator shouldn't change route then merely record state by dispatching it.

There are projects that tried that but they bumped into some inherent difficulties because it's essentially a two-way binding, and it's not very easy to get it right.

So yes, in theory URL derived from state would be cool. In practice it's harder because user can also directly the URL directly by going back and forward in history. Add to this asynchronous transitions and data loading, and it quickly gets complicated.

Redux is not dogmatic so use what you will. You can certainty follow a "purer" approach (check out redux-loop and redux-elm for examples of that). You can follow a "middle" approach with something like redux-saga. Or you can do the "easy" thing like redux-thunk. All of these approaches have their own merits.
