### ISSUE TITLE
Docs: Add example how to test reducers with async action creators

### ISSUE THREAD

**Issue by syndbg** [reactjs/redux#1912]
Currently I'm wondering how must an async action creator be tested against a reducer.

http://redux.js.org/docs/recipes/WritingTests.html gives a great overview how to test async action creators only, but not against a reducer.

Am I missing something here?

**Comment by Koleok** [comment]
You shouldn't really need to involve the reducer in async testing, since it will just have normal actions dispatched to it **after** the async things are completed.

So just test the reducer with normal _action/expectation_ pairs with each of the possible actions that might be dispatched after the async things resolve.

This might feel less cohesive but that is a good thing, it makes them unit tests :)

**Comment by Koleok** [comment]
This is coming from personal experience since this is how i set up all my redux testing, if its unclear what I'm getting at here I'd be glad to put up a gist or something.

**Comment by markerikson** [comment]
Yeah - generally you'd want to test that the action creator actually dispatches certain actions without caring how they might be interpreted, and test the reducer to verify its behavior based on state+action pairs.

You may be interested in some of the articles on [Redux-related testing](https://github.com/markerikson/react-redux-links/blob/master/react-redux-testing.md) that I have in my React/Redux links list - plenty of examples in there.
