### ISSUE TITLE
Anchor links on http://redux.js.org do not work in Firefox

### ISSUE THREAD

**Issue by kumar303** [reactjs/redux#1982]
**Do you want to request a *feature* or report a *bug*?**  

This is a bug report about http://redux.js.org/

**What is the current behavior?**

When I open a new tab in a browser and load http://redux.js.org/docs/basics/UsageWithReact.html#containersfilterlinkjs (or anything with an anchor), it behaves differently across browsers:

* On Firefox 49, the URL changes to http://redux.js.org/docs/basics/UsageWithReact.html but it does not show the `#containersfilterlinkjs` section, titled `containers/FilterLink.js`
* On Chrome 53.0.2785.116, the URL changes in the same way but I see the `containers/FilterLink.js` section

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

(see above)

**What is the expected behavior?**

* It should show the linked anchor section in Firefox
* The URL should retain the anchor so that I can easily copy and paste the link to share it with someone

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

N/A

This is also broken in development versions of Firefox

**Comment by markerikson** [comment]
@timdorr : see, I did say I was having issues with this (per https://github.com/reactjs/redux/pull/1891 )

**Comment by timdorr** [comment]
Gah! Stupid plugin is stupid. Is there a better gitbook plugin for anchoring?

**Comment by gaearon** [comment]
Would be cool to replace Gitbook with something that has better user experience.

**Comment by markerikson** [comment]
I guess the main question is, what _specific_ value and benefits does Gitbook bring to the table?  Off the top of my head:

- It parses and transforms Markdown
- It sets up the TOC
- It's got a built-in theme
- It's written in JS

Beyond that... ?

There's certainly plenty of other static site generators out there.  I just set up my own blog using Hugo, which is a single-binary Go app.  There's SSGs written in Javascript, including Gatsby, which is written in React.

Then again, it'd be nice to know why Gitbook is acting screwy this way.  Is there a relevant issue open?

Thoughts?

**Comment by timdorr** [comment]
BTW, we have a neat new custom website for React Router 4.0: https://github.com/ReactTraining/react-router/tree/v4/website There isn't the automatic ToC building, which is the one unique feature of Gitbook. But it's also a bit of magic and means you have to use a relatively opaque convention to your ToC document. Could be a potential starting point if Gatsby doesn't rub you the right way.

**Comment by markerikson** [comment]
Possibly related: https://github.com/GitbookIO/gitbook/issues/1402 , https://github.com/GitbookIO/gitbook/pull/1467 , https://github.com/GitbookIO/gitbook/issues/1337 .  Also https://www.gitbook.com/book/seadude/learn-gitbook/details .

**Comment by MoOx** [comment]
Maybe you might be interested by [Phenomic](http://phenomic.io/), a modern static website generator based on React (and webpack) which offer you a way to iterate on pages data :)

**Comment by SamyPesse** [comment]
Hi everybody!

First of all, we are taking a look at this exact bug to release a fix on GitBook ASAP.

@gaearon I understand that there is some frustration with the current GitBook UX. We are working hard on fixing it (both on GitBook, GitBook.com and the GitBook Editor).

But our goal is to transform GitBook into the perfect static generator / CMS for documentation. I believe it can become the right solution for projects like Redux.
We are starting to work more closely with open source projects to move GitBook in the right direction.

@markerikson Here is a list of what GitBook (and GitBook.com integrated with GitHub) can provide:

- GitBook Toolchain
   - Easy to setup in a GitHub repository (GitBook only requires a `book.json` file)
   - Search (also possible to integrate [Algolia](https://github.com/GitbookIO/plugin-algolia))
   - [We are working on better APIs for plugins](https://github.com/GitbookIO/gitbook/pull/1543)
   - Clean design by default
   - Still readable on GitHub
   - PDF builds (Not useful for projects like Redux)
- GitBook.com
    - Keep GitHub as the single source of truth
    - [HTTPS and CDN](https://www.gitbook.com/blog/features/gitbook-cdn)
    - CI for keeping `redux.js.org` always up to date
    - Edition with our [GitBook Editor](https://www.gitbook.com/editor)

But more importantly, the next versions of GitBook will be able to fit your use case better, since it will offer a simple and robust API to help developers build additions to GitBook.

Anyways, whatever you decide to drop GitBook or not, I'd love to get your feedback and advices on what we are doing and what we can do better :)

**Comment by timdorr** [comment]
OK, just rebuilt and this appears to work A-OK: http://redux.js.org/docs/recipes/reducers/UpdatingNormalizedData.html#other-approaches

Thanks for reaching out @SamyPesse and for the fixes. Please keep us in the loop as you have other changes coming down the pipeline. I'll probably look into the Algolia stuff pretty soon, as I'm a fan of their service.
