### ISSUE TITLE
Boilerplate Reduction + Improved TypeScript Support

### ISSUE THREAD

**Issue by bencompton** [reactjs/redux#2048]
I built a Redux add-on that I call [redux-retro](https://github.com/bencompton/redux-retro). It is essentially syntactic sugar on top of Redux that provides action syntax similar to libraries like Alt.js and others (auto-generated type strings, auto-dispatch, etc.), while introducing new reducer syntax (still pure functions). In addition, it also provides the ability to strongly type actions and reducers with TypeScript.

Much like with Flux, I realize that not everyone is a fan of such syntax "enhancements" in Redux, but I felt there is sufficient demand to merit an add-on for those who do like it. Also, I have yet to come across a solution for strongly typing actions and reducers, and that was much of the motivation for creating this library.

I am in the process of building a fairly complex app with the library, and it is working very well so far. The library is still a WIP (working examples coming soon), but I thought I'd post here to see if anyone would be kind enough to provide some feedback.

Edit: 

Rewrote to be more concise :)

**Comment by markerikson** [comment]
Yeah, for what it's worth, there's actually numerous examples of this type of addon/wrapper already.  I've got a ["Variations"](https://github.com/markerikson/redux-ecosystem-links/blob/master/variations.md) page in my Redux addons catalog, which is where I list libraries that take Redux in some direction that's different than the core idiomatic usages.  As you can see, there's quite a few items listed, and several of those take a similar approach of adding OOP wrappers, "removing actions", etc.  

While there's obviously some level of interest in this direction (otherwise people wouldn't be writing these wrappers), I personally don't see much of a point.  On which note: a few months back the author of another one of these OOP wrappers posted on HN asking why his wrapper wasn't getting any traction.  I wrote a fairly lengthy reply, describing why libraries like this tend to stay relatively obscure: https://news.ycombinator.com/item?id=11833301 .

So, overall: if this library works for you, great!  But, between the number of similar existing libraries and the overall mindset of the Redux community, I wouldn't expect it to pick up significant usage.

**Comment by bencompton** [comment]
Thanks for taking the time to give me the straight dope and helping me to direct my open source efforts more productively.

**Comment by markerikson** [comment]
To clarify, definitely don't want to discourage you from working on it, just pointing out some related/prior art and some thoughts on the topic.
