### ISSUE TITLE
missing return in state.map in TOGGLE_TODO action of the basic demo in the docs

### ISSUE THREAD

**Issue by maltepet** [reactjs/redux#2069]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
The reducer for `TOGGLE_TODO` returns an array of `undefined` resulting in an error preventing the task from switching completed state

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

- Create a todo
- Click the todo
- Error gets thrown

**What is the expected behavior?**
The todo switches its completed state

**Which versions of Redux, and which browser and OS are affected by this issue? Did this work in previous versions of Redux?**

**Comment by markerikson** [comment]
The existing code looks like it should work as-is.  It's using an implicit return from the arrow function.  Do you have an actual running example that shows it breaks, or are you just looking at the code?

**Comment by maltepet** [comment]
I had been following along with the tutorial and kept getting errors thrown when trying to toggle an item. Adding the return fixed it for me.

**Comment by markerikson** [comment]
Hmm.  That code _should_ work as is.  When you say "following along", how were you using/writing the code?  Copy/paste, or re-typing it yourself?  Is it possible that you have curly braces after the `=>`?  ES6 arrow functions have several quirks of syntax, one of which is that implicit return statements only work if there are no curly braces (otherwise the compiler interprets the curly braces as opening up the body of the function).

**Comment by maltepet** [comment]
Dang, sorry. yeah, I had put curly braces.

**Comment by markerikson** [comment]
Heh.  Yeah, definitely a syntax issue that's caused confusion for others before.  No worries :)  Thanks for trying to help tweak the docs.

FYI, I have links to a number of useful articles on [ES6 features and syntax](https://github.com/markerikson/react-redux-links/blob/master/es6-features.md) that may be helpful for you.
