### ISSUE TITLE
Discussion: Snapshot testing actions/reducers

### ISSUE THREAD

**Issue by khankuan** [reactjs/redux#2084]
Hi, I'm wondering if it is a practical idea to use snapshot testing for action creators as well as reducers. Found an article that describe what it might look like: https://blog.callstack.io/unit-testing-react-native-with-the-new-jest-ii-redux-snapshots-for-your-actions-and-reducers-8559f6f8050b

I feel that action creators and reducers are quite declarative and snapshot testing them might be relevant. 

Has anyone used/considered snapshot testing redux?

**Comment by timdorr** [comment]
That's certainly a valid use. The only issue is when you run into more advanced use cases, like action creators that create side effects or redux-saga stuff. Then you may not be able to snapshot the results from your action creators.

Reducers, being pure functions, should always be snapshot testable. I'm not 100% getting that detailed with your tests has much value. I think having more integrated tests, such as combing an action, reducer/dispatch, and selector together, gives you more value from your tests because you still know if most things break, but you don't have to go through the monotony of creating tons of unit tests.
