### ISSUE TITLE
Add info on use of ES6 to the docs?

### ISSUE THREAD

**Issue by markerikson** [reactjs/redux#2090]
A Reddit comment [pointed out that the Redux docs use ES6](https://www.reddit.com/r/programming/comments/5c13cp/someone_said_learning_angular_was_excruciating_so/d9t87ne/), but don't really offer any advice or info on how to use ES6 properly.  We've got the example projects configured to use `create-react-app`, but could we better highlight the need for ES6 and CRA in the various tutorial pages?

**Comment by timdorr** [comment]
Honestly, this feels really out of scope for the project. If you're using Redux, you've probably already picked up React or another library already (since you'll want something to plug Redux into) and have already tackled these kinds of problems.

Also, the need for transpilation is rapidly diminishing. I use [arrow functions as my benchmark](http://caniuse.com/#feat=arrow-functions) and we're 2/3rd of the way to not needing to transpile es2015 code. At that point, it's just Javascript.

**Comment by keepitreal** [comment]
I think a simple note at the beginning of the basics tutorial would be worth it. As @timdorr noted much of the es2015 syntax has made it into modern browsers. That said, certain parts of the docs (again, the basics section) use the es2015 import syntax which won't work in any environment I know of without transpilation. I agree that its out of scope to teach users Babel or some other transpiler but I still think its worth it, for clarity sake, to include at least a note or warning to the new user.

**Comment by timdorr** [comment]
I'm going to put a veto on this for now. We don't need to expand the scope of the docs to start explaining language features.
