### ISSUE TITLE
Donations to project

### ISSUE THREAD

**Issue by kandros** [reactjs/redux#2153]
Does redux have a way to accept donations such as https://opencollective.com or directly?

**Comment by markerikson** [comment]
I have to say I'm not really sure how the whole "donations to a project" thing works.  Maybe @TheLarkInn can pop in and share some thoughts on how Webpack uses donations.

(Obligatory tagging of @gaearon , @timdorr , and @jimbolla for thoughts as well.)

**Comment by gaearon** [comment]
If current Redux maintainers would like to accept donations I’m all for it.
I think the important part of this is to have a clear roadmap of deliverables and a plan.

**Comment by TheLarkInn** [comment]
We leverage donations in a variety of ways. Simply speaking the core team logs our hours on a monthly basis, and then based on the current monthly allowance (since 90% of funds are deposited on a monthly level), we can take x% of the max available amount. 

I personally have only used our funds so far for tee shirt design commission payment, I plan to reserve mine in the case that a conference can not find a particular flight for speaking at a conference about webpack, and if needed I'll dip into those funds. Otherwise, there are other ancillary things we plan to use funds for like bountysourcing particular issues/features etc.

**Comment by timdorr** [comment]
I'm ambivalent. While I definitely appreciate what a monetary donation says (it says a lot!), I'm not driven by financial gain to do OSS work. I mean, I did *just* buy a new house and car, so I'm good 😄  

I think the idea of saving those funds to afford trips to conferences could be interesting. Either that or diverting them to other projects/charities that could stand to benefit.

**Comment by markerikson** [comment]
Yeah.  I mean, I just sank 20+ hours into a 6000-word tutorial blog post on Redux usage, with accompanying sample code.  I definitely didn't do it because I'm trying to make money off of this :)

If Redux was under heavy active development, or there were a whole bunch of requested features that people had thrown out there that just needed time to implement, or there were lots of people all offering up donations, then maybe the situation would be different.  As things stand at the moment, though, none of those things are true.  My inclination would be to say "thanks", and redirect the request to a worthier cause.

**Comment by timdorr** [comment]
I think I'll just close this out as a "thank you, but no, we're not accepting donations at this time."

**Comment by markerikson** [comment]
But... but... MAH MONEYS!!!!

Nah, I agree with that decision.
