### ISSUE TITLE
createNamedWrapperReducer causes undefined initial state

### ISSUE THREAD

**Issue by robcalcroft** [reactjs/redux#2161]
Using the `createNamedWrapperReducer` function specified here http://redux.js.org/docs/recipes/reducers/ReusingReducerLogic.html stops initial state being calculated and reducer returns `undefined` which throws an error. I've worked around this by adding a `state !== undefined` clause to the `if` in `createNamedWrapperReducer`. Is this the correct way to resolve this or am I missing a step?

**Comment by markerikson** [comment]
Hmph.  This is what I get for writing example code without actually trying to run it :)

Yeah, now that you mention it, you're probably seeing an error that complains about a reducer returning `undefined`, aren't you.  That'd be because when `combineReducers` sends out a "probing" action to ensure all the reducers behave as expected, this wrapper reducer is just returning `undefined`.

I _think_ this rewritten version might work better:

```js
function createNamedWrapperReducer(reducerFunction, reducerName) {
    return (state, action) => {
        const {name} = action;
        if(state === undefined || name === reducerName) {
            return reducerFunction(state, action);    
        }
       
        return state;
    }
}
```
Lemme know if that works better for you.
