### ISSUE TITLE
combineReducers throws no error when something is wrong

### ISSUE THREAD

**Issue by mtrabelsi** [reactjs/redux#2188]
**How to reproduce**
My original code that works : 

```
export default combineReducers ({
	control,
	filter,
	todos
})
```
Then, I accidently duplicated the 'todos' in the combineReducers argument, where 'todos' is an array of object : 

```
export default combineReducers ({
	todos,
	filter,
	todos
})
```

After this change, my todolist app becomes silently broken - stopped working, and no error is thrown in the chrome console! 

**What is the expected behavior?**
Redux should throw an error, like ' you're using the same key twice ! please check your arguments '

**Which versions of Redux, and which browser and OS are affected by this issue?**

3.6.0 redux version, chrome running on windows 7 - didn't test on other enviroments

**Spent 1h to figure out what going on**

**Comment by markerikson** [comment]
I... don't _think_ there's anything Redux can do about this.  In Javascript, when you define duplicate keys on an object, the "later" value overrides the earlier one.  For example:

```js
const obj = {
  a : 42,
  b : 123,
  a : 99,
};

console.log(JSON.stringify(obj));
// {a : 99, b : 123}
```

In this example, you're defining `todos` twice, with the same value, so nothing changes there.  The real problem is that you're no longer including your `control` reducer, which presumably breaks the rest of the app.

So, as far as I can see, this is just as matter of how Javascript works.

**Comment by vaclavbohac** [comment]
I'd just add you can catch this kind of errors in your app by static analysis - here's `eslint` rule that would catch this http://eslint.org/docs/rules/no-dupe-keys
