### ISSUE TITLE
Changing a value from null to false / false to null doesn't trigger a rerender

### ISSUE THREAD

**Issue by GautierT** [reactjs/redux#2260]
Hi. 
I'm using redux-form to manage my input.
When i change a value with `input.onChange()` from `null` to `false` i can see the change in the store. (It's the same for `false` to `null`)
![image](https://cloud.githubusercontent.com/assets/6089653/23253764/fe55820a-f9b5-11e6-91c7-ce791dcfdd5c.png)
![image](https://cloud.githubusercontent.com/assets/6089653/23253774/04aa8e66-f9b6-11e6-988c-f10bc736b6ad.png)

But the component is not rerender. and `shouldComponentUpdate` is not called either.
Is this normal behavior ?

P.S : Changing from `null` to `true` does trigger a rerender and `true` to `false` too.

**Comment by markerikson** [comment]
It's difficult to say anything without seeing actual code.  The usual reason for this is accidental mutation in a reducer, per http://redux.js.org/docs/faq/ReactRedux.html#react-not-rerendering .  Since this is almost definitely not a bug with Redux itself, it should really be asked over on Stack Overflow instead.
