### ISSUE TITLE
Fix MiddlewareAPI in .ts

### ISSUE THREAD

**Issue by gorshkov-leonid** [reactjs/redux#2362]
MiddlewareAPI should have 2 params in type same as  [flow-typed/redux.js](https://github.com/reactjs/redux/blob/master/flow-typed/redux.js#L12-L15):

https://github.com/reactjs/redux/blob/master/index.d.ts#L256-L259

**Comment by aikoven** [comment]
Should it? Dispatch is able to accept any action, not just a specific subtype of `{type: string}`.

**Comment by gorshkov-leonid** [comment]
click on links please...

**Comment by aikoven** [comment]
I did. 

State type is generic because it depends on your state shape. 

Actions are not restricted to any subtype of `{type: string}`: dispatch accepts any object with `type` property, even if actions in your codebase are all of the specific shape e.g. `{type: string, payload: object}`. Imagine a third-party library that has its own action shapes.

Also, there might be a misconception with the generic parameter of `Dispatch`: the `S` in `Dispatch<S>` is not the action type, but the state type. You may notice that `Dispatch` signature doesn't even use this parameter:
```ts 
interface Dispatch<S> {
    <A extends Action>(action: A): A;
}
```
The reason for this is to allow middlewares to augment this interface with custom signatures, i.e. `redux-thunk`. See https://github.com/reactjs/redux/pull/1537

**Comment by timdorr** [comment]
@aikoven is correct here. Because you can enhance the store with middleware to accept any type of input as an "action", it needs to be generic.

**Comment by gorshkov-leonid** [comment]
OK. I understood. Yes it is logical. But it is not clear at first sight. Flow js - 2 type parameters. Ts - 1 type parameter. Think you need to leave a comment in code for the descendants
