### ISSUE TITLE
Fiber-like behaviour in Redux

### ISSUE THREAD

**Issue by Janther** [reactjs/redux#2383]
**Feature**

After watching [A Cartoon Intro to Fiber](https://www.youtube.com/watch?v=ZCuYPiUIONs&t=4s), it occurred to me that the principles of fiber could apply also to redux.

There are actions with higher priority than others, units of work could be each reducer function registered via `combineReducers` actions could be enqueued and high priority actions could be added in front of the queue and work partially done could be reused afterward if that portion of the state wasn't changed by the high priority action.

Double buffering could be used to switch between the current state and work in progress state.

The only API change, that I see here, is that actions would need a reserved optional `priority` key alongside with `type`.

**Comment by Janther** [comment]
After thinking a bit about this idea I think it would be a better fit to build this implementation as an `enhancer` for the store instead of a core functionality of Redux (at least as a proof of concept).

**Comment by gaearon** [comment]
The problem is the synchronous reducer signature and that reducers call each other directly.

**Comment by Janther** [comment]
Yeah been thinking a way around that, perhaps is only something that could work on the first level.
Although normalization of the store would make in theory this first level broad enough.

Will give this idea a few more thoughts.

**Comment by timdorr** [comment]
> The problem is the synchronous reducer signature

Even before that, `dispatch` is assumed to be synchronous. Notifying subscribers is where one could introduce asynchronicity, but that wouldn't be able to distinguish units of work, since the work is already done at that point.

@Janther You're right that is better handled as an enhancer. I could see you overriding dispatch to support batching. [Dan tweeted about this](https://twitter.com/dan_abramov/status/656074974533459968?lang=en) and I found at least [one library implementation](https://github.com/tshelburne/redux-batched-actions), so it's not unprecedented. How you execute those batches is where you can go wild. You could apply a Fiber-like stack implementation that executes work within a certain timeframe and only commits changes along rIC or rAF borders.

I am a tiny bit dubious on the performance benefits, though. Most reducers and actions are rather simple and therefore fast to dispatch. So, it would be very odd if you're manipulating so much state that you need to batch and break up the work into units. It's certainly indicative of other problems (such as an over-reliance on global state). It might better to attack other sides, such as on react-redux once Fiber exposes and API for us to indicate priority.

**Comment by markerikson** [comment]
For what it's worth, there's at least four ways to implement some kind of action batching strategy, with various tradeoffs:

- Higher order reducer that looks for `{type : "BATCH", actions : []}`
- Some kind of middleware
- Store enhancer that debounces notifications
- Store enhancer that accepts an array of actions and only notifies once


The headline sounds nifty as a phrase, but given Redux's design constraints, I'm not sure it's really applicable.  The main point of Redux is to do synchronous updates to state, one at a time.  As Tim said, executing the entire reducer structure _should_ generally be very fast, even for large apps, and so it's unlikely that doing so would block the event thread long enough to be a concern.

I'm going to say this isn't anything we would want to tackle ourselves, so I'll close this.  However, if you do put together an enhancer or some other kind of potentially useful addon, please drop a comment here and show us what you've got, and we can discuss things further.

**Comment by gaearon** [comment]
(FWIW I agree the real work is usually in re-rendering components, not in calculating the state.)
