### ISSUE TITLE
Confused: Why use for loop to create a finalReducers in combineReducers.js

### ISSUE THREAD

**Issue by Oscar-ren** [reactjs/redux#2492]
Recently, I read the Redux source code, and I confused in function [combineReducers.js#105](https://github.com/reactjs/redux/blob/master/src/combineReducers.js#L105)

```javascript
function combineReducers(reducers) {
  const reducerKeys = Object.keys(reducers)
  const finalReducers = {}
  
  // We create a new object to replace the param reducers
  // And use this new object to calculate the new state
  for (let i = 0; i < reducerKeys.length; i++) {
    const key = reducerKeys[i]
    if (typeof reducers[key] === 'function') {
      finalReducers[key] = reducers[key]
    }
  }
  // and so on ......
}
```

I don't understand why use a lot of code to traverse the reducers, is there something special？

As I think, better to use `const finalReducers = Object.assign({}, reducers)`, and the `typeof function` can place it on the next for loop, such as

```javascript
for(let i = 0; i < finalReducerKeys.length; i++) {
  const key = finalReducerKeys[i];
  const previousStateForKey = state[key];
  // here to typeof reducers[key]
  if(typeof finalReducers[key] === 'function') {
    const nextStateForKey = finalReducers[key](previousStateForKey, action);
    nextState[key] = nextStateForKey;
    hasChange = hasChange || nextStateForKey != previousStateForKey;
  }
}
```

This is the place where I am confused, by reading the source code, I learn a lot. 

Hope to receive your reply, thanks

**Comment by timdorr** [comment]
It lets us do two things: 

1) Filter the provided reducers to a smaller set, which is faster to operate on. 
2) Run sanity checks earlier, so that we don't have to bail out in the middle of combining the reducers.

This is common throughout the code. The bulk of Redux's code is sanity checks for the developer's sake. This is often done before the actual important code is run. This just throws in a little micro optimization into the mix.
