### ISSUE TITLE
Allow ReduxStore to callback subscribers event methods, not only the onStateChange(StoreState).

### ISSUE THREAD

**Issue by pablichjenkov** [reactjs/redux#2504]
**Do you want to request a *feature* or report a *bug*?**  

Request a feature

Hi there, I am working with an implementation of Redux for Android. The Kotlin library API is the same API as defined by the redux specs, no difference other than the language. I am having some problems with detecting specific Store events. Normally a component has only one interaction with the store, this is through the event onStoreChange(State currentState). With Presentational components there is no problem, because they only render the component props into the view. But, what happen if I have a Container component that needs to add/remove child components depending on a Store specific event.
In other words, the only information that a Store gives to a subscriber is the Store State itself, we can compare the previous state against the current state to determine the event that just happened, but its high performance. Another option to detect a specific event could be having an event map in the State and mark them with true/false as they happen. Then the subscribed component will check this map and act accordingly to the active event. 
However, I consider that the easiest way to inform a component about specific events in the State is to subscribe an StoreEventsListener object from the component, that will receive callbacks associated with specific Store events. 
Is this something that breaks the rules of redux?

**Comment by markerikson** [comment]
Typically, what a connected parent component will do is have its `mapState` function gather a list of items it wants to display.  These could be either the actual data objects themselves, or IDs for the individual items.  Then, the list component will map over the items and pass those to its children.  For example, a `TodoList` component will either render children like `<TodoListItem todo={todo} />` (if the child is not connected), or `<TodoListItem id={todoId} />` (if the child is connected).

That way, the parent isn't actually having to "decide" which items are added or removed - it just displays whatever the current list of items is.

Beyond that: yes, in general, the "React way" of doing things is to drive behavior based on state.  That means that typically, instead of doing something like triggering a pub/sub event like `"specific:update:event"` and responding to that, you would use a component's `componentWillReceiveProps` method to see if a specific prop value is in the process of changing (such as `if(this.props.someValue !== nextProps.someValue)`.

So, it's a bit less about "specific rules", and more about "how these are normally used".

**Comment by pablichjenkov** [comment]
@markerikson Thanks for your response. I was using redux as a handy tool for implementing my State Machines in general, not only for components. I think Redux can be used as a good implementation of the State Pattern. If we see Reducers as a "next state" resolver functions and the Store as the States container. Then replaceReducer(Reducer nextReducer) has the same effect as setNextStateHandler() in the State Pattern. I like the way Redux has been thought and I don't want to break "how Redux is normally used" so I will create "Detectors" to verify when/what/how certain session of the data change on the componentWillReceiveProps(State storeState) call.
