### ISSUE TITLE
Broken HTTPS on https://reactjs.org

### ISSUE THREAD

**Issue by mickeyreiss-visor** [reactjs/redux#2616]
I'm currently seeing an security certificate error on https://reactjs.org in Google Chrome Version 60.0.3112.113.

![image](https://user-images.githubusercontent.com/30812527/30609613-bd186928-9d30-11e7-8348-d06880257205.png)
![image](https://user-images.githubusercontent.com/30812527/30609617-c28767ec-9d30-11e7-9ba2-45542f477cda.png)
![image](https://user-images.githubusercontent.com/30812527/30609636-cfc31b22-9d30-11e7-9f5b-eaaac8abd4dd.png)
![image](https://user-images.githubusercontent.com/30812527/30609658-dec1dba4-9d30-11e7-8c05-775b47bc6f35.png)

**Comment by timdorr** [comment]
The docs site doesn't work in HTTPS. It's hosted by GitHub, so they don't have a cert for js.org.

**Comment by indus** [comment]
@timdorr JS.ORG is using Cloudflare and they provide "Universal SSL" - so it is easily possible to get HTTPS.

Back then when the "redux" subdomain was added to JS.ORG, SSL support was an opt-in. But you didn't took the option. Now it is the default, but owners of "old" subdomains have to make a PR to change it.
The reason for so little enforcement is that pages may show mixed-content warnings if e. g. paths to CSS  where set absolute or other non-HTTPS content was included.
So switching would be easy but it has to be triggered by you. Just file a PR that removes the comment in [that line](https://github.com/js-org/dns.js.org/blob/master/cnames_active.js#L765)

I'm writing to you because @jlebensold asked me on twitter why you don't have HTTPS

**Comment by timdorr** [comment]
Hmm, looks like we also need to update that URL, since the rackt org (since disbanded) has been typosquated. Thanks for the heads up!
