### ISSUE TITLE
Show diff of old and new state

### ISSUE THREAD

**Issue by ralcon** [reactjs/redux#2734]
Hi folks,

I'm a react-native developer and because of my growing application, i want to develop with redux to use all the benefits for handling state.

My questions is:
Is there a way to identify differeces between the old and the new state, without comparing the state programmatically/manually?

I think of a method like that:
```
oldState = {name: 'Sandra', age: 5, address: 'this street'}
newState = {name: 'Sandra', age: 6, address: 'this street', favColor: 'blue'}
diffState = showStateDiff(oldState, newState)
// where diffState will be {age: '6', favColor: 'blue'}
```

I saw something like that in redux-devtools, where the differences are shown in the diff tab.

Any help? Thank you in advance!

**Comment by timdorr** [comment]
State shouldn't be concerned with transitional/differential information. If you're doing that, you're likely writing imperative code, whereas declarative code is better because you can ignore complexities like time. 

But if you need to represent a some sort of difference, encode that into the state tree as a part of your reducer. Add a `lastChange` key or something to that effect.
