### ISSUE TITLE
Todos example uses anchor element instead of button

### ISSUE THREAD

**Issue by lazarljubenovic** [reactjs/redux#2764]
**Do you want to request a *feature* or report a *bug*?**  Report a **bug** in documentation.

**What is the current behavior?**
The [`Link` component in `todos` example app](https://github.com/reactjs/redux/blob/master/examples/todos/src/components/Link.js) uses an anchor element with a dummy href `#`, and then it `preventDefault`s the native action. The application makes no use of routing.

**What is the expected behavior?**
A link that doesn't go anywhere is **not a link**. It's a **button**. To favor semantics (and thus make the app more accessible), it should be changed to button. The code will also be simplified then, as there will no longer be need to call `preventDefault` which in turn makes `onClick` inlineable.

---

I know it doesn't matter for the example, but using proper semantics in this case is really easy (even easier than current implemntation). It's a very important thing to know on the long run (unfortunatelly neglected by a huge portion of developers), and many new developers develop habit of using anchor tags for buttons exactly from these introductionary tutorials.

**Comment by xRahul** [comment]
Hey @lazarljubenovic I agree that if there's a link that doesn't go anywhere and we have a script associated with it's click it should be a button for better UI. 
But, in this case, you're associating `Link` component with the `FilterLink`. Pure Link component is used to replace any links on the webpage. You can not assume all the links will behave like a button.
Also, you'd lose the `children` part available in the Link component. Link component can wrap anything and make that clickable, while the button tag won't be able to do so.

**Comment by lazarljubenovic** [comment]
I'm not sure I understand the reasoning. _Why_ do we use Link component which is a wrapper around an anchor element in the first place? Why not make a `FilterButton` which wraps around a native `button` and use it instead?

**Comment by timdorr** [comment]
This is basically a precursor to a `<Link>` component in a routing library. The only reason the href isn't populated is because the "routing" being done here isn't URL-based. 

It's fine as-is because the next step a user would take is to add a routing library. That's out of scope for a simplified example, but it's a good idea to set them up for that path.

**Comment by xRahul** [comment]
This is used to follow the pattern and keeping api consistent. `Link` has become a standard and is easy to understand given it's widespread use.
`FilterButton` with `Button` can also be used here in the example without any issues, but this would just introduce new things to the user, giving them more things to process.
At the end, it comes to choice too. For me, creating `Link` component makes more sense as you can do everything a button can do and more. So why not use the more extensible version instead of specific.
