### ISSUE TITLE
Increase visibility of when to use Redux vs when not to use Redux in docs

### ISSUE THREAD

**Issue by dyst5422** [reactjs/redux#2797]
The docs currently has a section on the first page [Before Proceding Further](https://redux.js.org/#before-proceeding-further) which has a single link to a Medium article Dan wrote a year and a half back.

This effectively hides when NOT to use Redux behind a link and article post. I know dissuading people from using the library isn't a great way to do PR, but I think there are a LOT of people that get into using Redux for the wrong reasons or jump in too soon. The amount of overhead Redux requires leaves a sour taste in their mouth.

I propose a simple 3 big bullets when to use Redux and 3 big bullets of when NOT to use Redux, as well as perhaps suggestions for other tools that may fill certain use cases better.

**Comment by dyst5422** [comment]
As I was writing this, I thought of the use case of a client side data-cacheing layer where [Data Loader](https://github.com/facebook/dataloader) or [Apollo Client](https://github.com/apollographql/apollo-client) (if you're using GraphQL) would be a better option in the alternative tools section.

**Comment by markerikson** [comment]
Yeah, Dan has honestly spent more time telling people to _not_ use Redux than he has promoting it :)  And yes, there are some valid reasons why he's had to adopt that sort of approach.

I'd be very happy to take a PR that updates that section.  I'd suggest looking at the FAQ entries for [When should I use Redux?](https://redux.js.org/docs/faq/General.html#general-when-to-use) and [Can I split state between Redux and React component state?](https://redux.js.org/docs/faq/OrganizingState.html#organizing-state-only-redux-state), and summarize the points in those answers.

Also, my two posts on [The Tao of Redux, Part 1 - Implementation and Intent](http://blog.isquaredsoftware.com/2017/05/idiomatic-redux-tao-of-redux-part-1/) and [The Tao of Redux, Part 2 - Practice and Philosophy](http://blog.isquaredsoftware.com/2017/05/idiomatic-redux-tao-of-redux-part-2/) _may_ be worth linking alongside "You Might Not Need Redux", since they provide context and background for why Redux is built the way it is and how it's intended to be used.

**Comment by markerikson** [comment]
Closed by #2851 .
