### ISSUE TITLE
React suspense

### ISSUE THREAD

**Issue by lmatteis** [reactjs/redux#2867]
With [React's new Suspense feature](https://reactjs.org/blog/2018/03/01/sneak-peek-beyond-react-16.html) I'm curious how it can be used along with Redux. 

Certainly looks like an exciting feature, and given that async was never a feature of Redux (have to use middlewares such as redux-thunk), maybe they can play along nicely.

Some critical points were already risen in the official PR https://github.com/facebook/react/pull/12279#issuecomment-370221500

**Comment by markerikson** [comment]
Yeah, we've got a lot to figure out going forward.  That said, whatever happens will be over at the React-Redux repo instead of the core Redux repo.  Jim Bolla opened up a notional early [experimental POC PR to better work with React 16](https://github.com/reactjs/react-redux/pull/856), but other than that, we're still trying to wrap our heads around what all this async rendering stuff means.  

I'll close this issue since any real discussion ought to happen over in the other repo instead.  But, we might as well open up an issue for general discussion there, even if we ourselves don't really know what our course of action is.
