### ISSUE TITLE
Refactoring examples to be more readable for beginners.

### ISSUE THREAD

**Issue by aungmyohtet** [reactjs/redux#2954]
This is my first issue on an open sourced github repository. So, sorry if I cannot explain well or make some mistakes.
I am referring to redux Example:Todo list. 

I will explain the problem by using a file [containers/VisibleTodoList.js/](https://github.com/reactjs/redux/blob/master/examples/todos/src/containers/VisibleTodoList.js)

But, I think,  it is a little difficult to understand for beginners.

```
import { connect } from 'react-redux'

...

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(TodoList)
```

The problem is the name `connect`
In this case, `connect` is not really a *connect* function. It is a function which creates a  *connect* function. If it is, someone can think why the code is not like:

```
export default connect(
  TodoList,
  mapStateToProps,
  mapDispatchToProps
)
```

When I check react-redux source code, the name is `createConnect`.
So, I wish the code should have been like:

```
import { createConnect } from 'react-redux'

...

export default createConnect(
  mapStateToProps,
  mapDispatchToProps
)(TodoList)
```

Or, to be more readable for beginners:

```
import { createConnect } from 'react-redux'

...

const connect = createConnect(
  mapStateToProps,
  mapDispatchToProps
)
export default connect(TodoList)
```

Because I think most beginners reach this redux tutorial before knowing what react-redux actually is.

**Comment by markerikson** [comment]
`createConnect` is an internal implementation detail of `connect`, and shouldn't matter to the end user.  As for the signature, it's written as a function returning a function so that you could in theory create a connection definition once, and reuse it with multiple components.

It might not be ideal, but it's been that way since the beginning.  So, it's not a question of "refactoring the examples", it's using the API that actually exists.
